Add upper bounding for targets
thedropbears/vision-2020 pull request #14
Opened 2020-02-19 09:46 UTC by djiang3099

Need to add polygon check for 'acceptable contours', oliver todo

2020-02-19 09:55 UTC, raulvera59 requested changes
Found another show and waitkey, but not in test code and without a timeout. Will hang the robot.

2020-02-19 09:55 UTC, raulvera59 commented on vision.py
> +                cv2.imshow("Display", self.display)
Oops. This one isn't in a test, and it doesn't have a timeout. This will hang the robot.

2020-02-19 10:14 UTC, raulvera59 approved these changes
LGTM

2020-02-21 08:15 UTC, Injector-Spenral approved these changes

2020-02-21 09:11 UTC, Injector-Spenral requested changes

2020-02-21 09:11 UTC, Injector-Spenral commented on magic_numbers.py
> +)
Why is that now a tuple?

2020-02-21 09:16 UTC, Injector-Spenral approved these changes

2020-02-21 09:17 UTC, merged